ver1
uranru/java-explore-with-me pull request #1
Opened 2022-11-22 16:21 UTC by uranru

2022-11-23 19:24 UTC, EvgenyKoptubenko commented
Это так на будущее: Когда пишешь коммент, то в нем должен быть идентификатор задачи и описание что было сделано в коммите.
Например, в данной задаче было бы здорово, если в коммитах было написано что было поправлено в каждом.

2022-11-23 19:43 UTC, EvgenyKoptubenko commented on main-service/src/main/java/ru/practicum/explore/category/controller/PublicCategoryController.java
> +    public CategoryDto getСategoryById(@PathVariable Long id,
в getCategoryById буквы C русская. Лучше использовать все символы английского языка

2022-11-23 19:44 UTC, EvgenyKoptubenko commented on main-service/src/main/java/ru/practicum/explore/category/controller/PublicCategoryController.java
> +        return categoryDto;
можно сразу писать return categoryService.getCategoryDtoById(id);

2022-11-23 19:44 UTC, EvgenyKoptubenko commented on main-service/src/main/java/ru/practicum/explore/category/service/CategoryService.java
> +public interface CategoryService {
все интерфейсы по умолчанию public

2022-11-23 19:47 UTC, EvgenyKoptubenko commented on main-service/src/main/java/ru/practicum/explore/category/service/CategoryServiceImpl.java
> +            throw new ResponseStatusException(HttpStatus.resolve(404), "");
Лучше не использовать числовые значения ответов, т.к. эти константы уже есть в HttpStatus
HttpStatus.BAD_REQUEST, например

2022-11-23 19:52 UTC, EvgenyKoptubenko commented on main-service/src/main/java/ru/practicum/explore/event/service/EventServiceImpl.java
> +        QEvent qEvent = QEvent.event;
Cannot resolve symbol 'QEvent'
Похоже не хватает какой-то библиотеки

2022-11-23 19:58 UTC, EvgenyKoptubenko commented on main-service/src/main/java/ru/practicum/explore/user/AdminUserController.java
> +    public UserDto addUser(@RequestBody UserDto userDto) {
Если добавить несколько одинаковых пользователей, то приходит правильный ответ 409, но при этом виден эксепшен от базы данных. Лучше пользователю видеть сообщение из разряда "Такой пользователь уже существует"
{
	"message": "could not execute statement; SQL [n/a]; constraint [uq_user_name]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement",
	"reason": "Integrity constraint has been violated",
	"status": "CONFLICT",
	"timestamp": "2022-11-23T19:57:15.535104"
}

2022-11-23 19:59 UTC, EvgenyKoptubenko commented on main-service/src/main/java/ru/practicum/explore/user/AdminUserController.java
> +        UserDto newUserDto = userService.addUser(userDto);
Если отправить неправильный запрос, то виден стек трейс
{
	"message": "Validation failed for classes [ru.practicum.explore.user.User] during persist time for groups [javax.validation.groups.Default, ]\nList of constraint violations:[\n\tConstraintViolationImpl{interpolatedMessage='must be a well-formed email address', propertyPath=email, rootBeanClass=class ru.practicum.explore.user.User, messageTemplate='{javax.validation.constraints.Email.message}'}\n]",
	"reason": "For the requested operation the conditions are not met.",
	"status": "BAD_REQUEST",
	"timestamp": "2022-11-23T19:58:59.820919"
}

2022-11-23 20:00 UTC, EvgenyKoptubenko commented on main-service/src/main/java/ru/practicum/explore/user/AdminUserController.java
> +    @DeleteMapping("/admin/users/{id}")
Если удалять несуществующего пользователя, то падает

{
	"timestamp": "2022-11-23T19:59:41.073+00:00",
	"status": 500,
	"error": "Internal Server Error",
	"path": "/admin/users/47"
}

org.springframework.dao.EmptyResultDataAccessException: No class ru.practicum.explore.user.User entity with id 47 exists!
2022-11-23T19:59:41.072496300Z 	at org.springframework.data.jpa.repository.support.SimpleJpaRepository.lambda$deleteById$0(SimpleJpaRepository.java:173) ~[spring-data-jpa-2.7.2.jar!/:2.7.2]
2022-11-23T19:59:41.072584800Z 	at java.base/java.util.Optional.orElseThrow(Optional.java:408) ~[na:na]

2022-11-23 20:04 UTC, EvgenyKoptubenko commented on stats-service/src/main/java/ru/practicum/explore/hit/service/HitServiceImpl.java
> +import ru.practicum.explore.hit.QHit;
Такого класса в репозитории нет

2022-11-23 20:04 UTC, EvgenyKoptubenko commented on stats-service/src/main/resources/schema.sql
> +                                          hit_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
поехало форматирование - слишком много отступов

2022-11-23 20:08 UTC, EvgenyKoptubenko requested changes
Замечаний практически нет. Код сделан хорошо

2022-11-24 15:01 UTC, uranru commented on main-service/src/main/java/ru/practicum/explore/category/controller/PublicCategoryController.java
> +    public CategoryDto getСategoryById(@PathVariable Long id,
исправил

2022-11-24 15:04 UTC, uranru commented on main-service/src/main/java/ru/practicum/explore/category/controller/PublicCategoryController.java
> +        return categoryDto;
исправил

2022-11-24 15:07 UTC, uranru commented on main-service/src/main/java/ru/practicum/explore/category/service/CategoryService.java
> +public interface CategoryService {
исправил для метода
 List<CategoryDto> findAllCategoryOrderById

2022-11-24 15:13 UTC, uranru commented on main-service/src/main/java/ru/practicum/explore/category/service/CategoryServiceImpl.java
> +            throw new ResponseStatusException(HttpStatus.resolve(404), "");
исправил

2022-11-24 15:21 UTC, uranru commented on main-service/src/main/java/ru/practicum/explore/user/AdminUserController.java
> +    public UserDto addUser(@RequestBody UserDto userDto) {
исправил

2022-11-24 15:27 UTC, uranru commented on main-service/src/main/java/ru/practicum/explore/user/AdminUserController.java
> +    @DeleteMapping("/admin/users/{id}")
исправил

2022-11-24 15:31 UTC, uranru commented on main-service/src/main/java/ru/practicum/explore/user/AdminUserController.java
> +        UserDto newUserDto = userService.addUser(userDto);
исправил

2022-11-24 15:32 UTC, uranru commented on stats-service/src/main/resources/schema.sql
> +                                          hit_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
исправил

2022-11-24 15:44 UTC, uranru commented on main-service/src/main/java/ru/practicum/explore/event/service/EventServiceImpl.java
> +        QEvent qEvent = QEvent.event;
Это связано с Query DSL
Нужно сделать mvn compile чтобы сгенерировались Q классы

2022-11-24 15:44 UTC, uranru commented on stats-service/src/main/java/ru/practicum/explore/hit/service/HitServiceImpl.java
> +import ru.practicum.explore.hit.QHit;
Это связано с Query DSL
Нужно сделать mvn compile чтобы сгенерировались Q классы

2022-11-24 15:45 UTC, uranru commented on main-service/src/main/java/ru/practicum/explore/event/service/EventServiceImpl.java
> +        QEvent qEvent = QEvent.event;
сказазали баг у идеи

2022-11-24 21:15 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо. На будущее, например, когда будут спрашивать на собеседовании, то в проекте еще должно быть:
* 		Healthcheck (отдельный эндпоинт, который возвращает данные о том как себя чувствует приложение) - например описать как работает Spring Actuator
* 		На основе Healthcheck можно делать мониторинг, который будет периодически дергать этот эндпоинт и если что-то в healthcheck сломалось, то присылает алерты
* 		Так же в проекте должна быть документация, которая автоматически собирается - Docsify, например
* 		Так что должно быть отдельное приложение, которое собирает проект, создает артифакт и складывает его в хранилище. В Github тоже можно такое сделать.
* 		Во время код ревью должен подключаться Sonar для проверок.
* 		Во время пул реквеста так же должно подсчитываться покрытие кода тестами
* 		Приложение должно быть защищено, т.е. неавторизованные пользователи не должны иметь доступ к эндпоинтам. Почитай про OAUTH2
* 		В пул реквестах должно быть настроено минимальное количество апруверов, которые должны проверить и заапрувить пул реквест перед тем как его можно мерджить
* 		Все должно быть покрыто юнит тестами, так же должны быть написаны BDD тесты.
* 		Все, что не дает коду пройти в прод называется Quality Gates. К таким quality gates можно причислить: jUnit tests, BDD tests, Sonar, Pull Requests checks, code coverage, Catchpoint tests, Performance tests, Browserstack tests.
* 		Так же в приложении должен быть код, который создает инфраструктуру. Например, если ты хостишься в Amazon, то через Terraform нужно создать инфру.
* 		Дополнительный мониториг бизнес фич. У тебя должны быть графики о том как дела у приложения и у клиентов. И так же настроены алерты, если что-то пошло не так.

2022-11-25 16:22 UTC, merged